export const NATIONALITIES = [
  {label: 'American', value: 'American'},
  {label: 'Canadian', value: 'Canadian'},
  {label: 'British', value: 'British'},
  {label: 'Australian', value: 'Australian'},
  {label: 'German', value: 'German'},
  {label: 'French', value: 'French'},
  {label: 'Italian', value: 'Italian'},
  {label: 'Spanish', value: 'Spanish'},
  {label: 'Brazilian', value: 'Brazilian'},
  {label: 'Mexican', value: 'Mexican'},
  {label: 'Indian', value: 'Indian'},
  {label: 'Chinese', value: 'Chinese'},
  {label: 'Japanese', value: 'Japanese'},
  {label: 'South Korean', value: 'South Korean'},
  {label: 'South African', value: 'South African'},
  {label: 'Nigerian', value: 'Nigerian'},
  {label: 'Egyptian', value: 'Egyptian'},
  {label: 'Russian', value: 'Russian'},
  {label: 'Saudi', value: 'Saudi'},
  {label: 'Argentinian', value: 'Argentinian'},
  {label: 'Uzbek', value: 'Uzbek'},
  {label: 'Pakistani', value: 'Pakistani'},
  {label: 'Bangladeshi', value: 'Bangladeshi'},
  {label: 'Dutch', value: 'Dutch'},
]
