export const COUNTRIES = [
  {
    label: 'Uzbekistan',
    value: 'Uzbekistan',
    cities: [
      {label: 'Tashkent', value: 'Tashkent'},
      {label: 'Samarkand', value: 'Samarkand'},
      {label: 'Bukhara', value: 'Bukhara'},
      {label: 'Andijan', value: 'Andijan'},
      {label: 'Namangan', value: 'Namangan'},
      {label: 'Fergana', value: 'Fergana'},
      {label: 'Nukus', value: 'Nukus'},
      {label: 'Khiva', value: 'Khiva'},
      {label: 'Termez', value: 'Termez'},
      {label: 'Kokand', value: 'Kokand'},
    ],
  },
  {
    label: 'United States',
    value: 'United States',
    cities: [
      {label: 'New York', value: 'New York'},
      {label: 'Los Angeles', value: 'Los Angeles'},
      {label: 'Chicago', value: 'Chicago'},
      {label: 'Houston', value: 'Houston'},
      {label: 'Phoenix', value: 'Phoenix'},
      {label: 'Philadelphia', value: 'Philadelphia'},
      {label: 'San Antonio', value: 'San Antonio'},
      {label: 'San Diego', value: 'San Diego'},
      {label: 'Dallas', value: 'Dallas'},
      {label: 'San Jose', value: 'San Jose'},
    ],
  },
  {
    label: 'Canada',
    value: 'Canada',
    cities: [
      {label: 'Toronto', value: 'Toronto'},
      {label: 'Vancouver', value: 'Vancouver'},
      {label: 'Montreal', value: 'Montreal'},
      {label: 'Calgary', value: 'Calgary'},
      {label: 'Ottawa', value: 'Ottawa'},
      {label: 'Edmonton', value: 'Edmonton'},
      {label: 'Winnipeg', value: 'Winnipeg'},
      {label: 'Quebec City', value: 'Quebec City'},
      {label: 'Hamilton', value: 'Hamilton'},
      {label: 'Victoria', value: 'Victoria'},
    ],
  },
  {
    label: 'United Kingdom',
    value: 'United Kingdom',
    cities: [
      {label: 'London', value: 'London'},
      {label: 'Manchester', value: 'Manchester'},
      {label: 'Birmingham', value: 'Birmingham'},
      {label: 'Liverpool', value: 'Liverpool'},
      {label: 'Leeds', value: 'Leeds'},
      {label: 'Glasgow', value: 'Glasgow'},
      {label: 'Edinburgh', value: 'Edinburgh'},
      {label: 'Bristol', value: 'Bristol'},
      {label: 'Sheffield', value: 'Sheffield'},
      {label: 'Cardiff', value: 'Cardiff'},
    ],
  },
  {
    label: 'Australia',
    value: 'Australia',
    cities: [
      {label: 'Sydney', value: 'Sydney'},
      {label: 'Melbourne', value: 'Melbourne'},
      {label: 'Brisbane', value: 'Brisbane'},
      {label: 'Perth', value: 'Perth'},
      {label: 'Adelaide', value: 'Adelaide'},
      {label: 'Canberra', value: 'Canberra'},
      {label: 'Hobart', value: 'Hobart'},
      {label: 'Darwin', value: 'Darwin'},
      {label: 'Gold Coast', value: 'Gold Coast'},
      {label: 'Newcastle', value: 'Newcastle'},
    ],
  },
  {
    label: 'Germany',
    value: 'Germany',
    cities: [
      {label: 'Berlin', value: 'Berlin'},
      {label: 'Munich', value: 'Munich'},
      {label: 'Hamburg', value: 'Hamburg'},
      {label: 'Frankfurt', value: 'Frankfurt'},
      {label: 'Cologne', value: 'Cologne'},
      {label: 'Stuttgart', value: 'Stuttgart'},
      {label: 'Düsseldorf', value: 'Düsseldorf'},
      {label: 'Dortmund', value: 'Dortmund'},
      {label: 'Essen', value: 'Essen'},
      {label: 'Leipzig', value: 'Leipzig'},
    ],
  },
  {
    label: 'France',
    value: 'France',
    cities: [
      {label: 'Paris', value: 'Paris'},
      {label: 'Marseille', value: 'Marseille'},
      {label: 'Lyon', value: 'Lyon'},
      {label: 'Toulouse', value: 'Toulouse'},
      {label: 'Nice', value: 'Nice'},
      {label: 'Nantes', value: 'Nantes'},
      {label: 'Strasbourg', value: 'Strasbourg'},
      {label: 'Montpellier', value: 'Montpellier'},
      {label: 'Bordeaux', value: 'Bordeaux'},
      {label: 'Lille', value: 'Lille'},
    ],
  },
  {
    label: 'Italy',
    value: 'Italy',
    cities: [
      {label: 'Rome', value: 'Rome'},
      {label: 'Milan', value: 'Milan'},
      {label: 'Naples', value: 'Naples'},
      {label: 'Turin', value: 'Turin'},
      {label: 'Palermo', value: 'Palermo'},
      {label: 'Genoa', value: 'Genoa'},
      {label: 'Bologna', value: 'Bologna'},
      {label: 'Florence', value: 'Florence'},
      {label: 'Venice', value: 'Venice'},
      {label: 'Verona', value: 'Verona'},
    ],
  },
  {
    label: 'Japan',
    value: 'Japan',
    cities: [
      {label: 'Tokyo', value: 'Tokyo'},
      {label: 'Osaka', value: 'Osaka'},
      {label: 'Yokohama', value: 'Yokohama'},
      {label: 'Nagoya', value: 'Nagoya'},
      {label: 'Sapporo', value: 'Sapporo'},
      {label: 'Fukuoka', value: 'Fukuoka'},
      {label: 'Kyoto', value: 'Kyoto'},
      {label: 'Kawasaki', value: 'Kawasaki'},
      {label: 'Saitama', value: 'Saitama'},
      {label: 'Hiroshima', value: 'Hiroshima'},
    ],
  },
  {
    label: 'Brazil',
    value: 'Brazil',
    cities: [
      {label: 'São Paulo', value: 'São Paulo'},
      {label: 'Rio de Janeiro', value: 'Rio de Janeiro'},
      {label: 'Brasília', value: 'Brasília'},
      {label: 'Salvador', value: 'Salvador'},
      {label: 'Fortaleza', value: 'Fortaleza'},
      {label: 'Belo Horizonte', value: 'Belo Horizonte'},
      {label: 'Manaus', value: 'Manaus'},
      {label: 'Curitiba', value: 'Curitiba'},
      {label: 'Recife', value: 'Recife'},
      {label: 'Porto Alegre', value: 'Porto Alegre'},
    ],
  },
]
