export const VISA = [
  {label: 'A-1 (외교)', value: 'A-1 (외교)'},
  {label: 'A-2 (공무)', value: 'A-2 (공무)'},
  {label: 'B-1 (사증면제)', value: 'B-1 (사증면제)'},
  {label: 'B-2 (간광통과)', value: 'B-2 (간광통과)'},
  {label: 'C-1 (일시취업)', value: 'C-1 (일시취업)'},
  {label: 'C-3 (단기방문)', value: 'C-3 (단기방문)'},
  {label: 'C-4 (일시취업)', value: 'C-4 (일시취업)'},
  {label: 'D-2 (유학)', value: 'D-2 (유학)'},
  {label: 'D-4 (일반연수)', value: 'D-4 (일반연수)'},
  {label: 'D-5 (취재)', value: 'D-5 (취재)'},
  {label: 'D-7 (협정)', value: 'D-7 (협정)'},
  {label: 'D-8 (기업투자)', value: 'D-8 (기업투자)'},
  {label: 'D-9 (무역경영)', value: 'D-9 (무역경영)'},
  {label: 'D-10 (구직)', value: 'D-10 (구직)'},
  {label: 'D-6 (종교)', value: 'D-6 (종교)'},
  {label: 'E-1 (교수)', value: 'E-1 (교수)'},
  {label: 'E-2 (회화지도)', value: 'E-2 (회화지도)'},
  {label: 'E-3 (연구)', value: 'E-3 (연구)'},
  {label: 'E-4 (기술지도)', value: 'E-4 (기술지도)'},
  {label: 'E-5 (전문직업)', value: 'E-5 (전문직업)'},
  {label: 'E-6 (예술흥행)', value: 'E-6 (예술흥행)'},
  {label: 'E-7 (특정활동)', value: 'E-7 (특정활동)'},
  {label: 'E-8 (계절근로)', value: 'E-8 (계절근로)'},
  {label: 'E-9 (비전문취업)', value: 'E-9 (비전문취업)'},
  {label: 'E-10 (선원취업)', value: 'E-10 (선원취업)'},
  {label: 'F-1 (방문동거)', value: 'F-1 (방문동거)'},
  {label: 'F-2 (거주)', value: 'F-2 (거주)'},
  {label: 'F-3 (동반)', value: 'F-3 (동반)'},
  {label: 'F-4 (재외동포)', value: 'F-4 (재외동포)'},
  {label: 'F-5 (영주)', value: 'F-5 (영주)'},
  {label: 'F-6 (결혼이민)', value: 'F-6 (결혼이민)'},
  {label: 'H-1 (관광취업)', value: 'H-1 (관광취업)'},
  {label: 'H-2 (방문취업)', value: 'H-2 (방문취업)'},
  {label: 'G-1 (기타)', value: 'G-1 (기타)'},
  {label: 'Other', value: 'Other'},
]
